### ISSUE TITLE
Show friendly sw360 error page or popup in case of an error

### ISSUE THREAD

**Issue by maierthomas** [sw360/sw360portal#685] opened 2017-11-20 09:33 UTC
If the users encounters a certain error such as 404 sw360 should display a friendly error page.
- like error-pages in web.xml

**Comment by mcjaeger** [comment] 2017-11-21 12:53
there is also the error case for readmes not being created.

**Comment by mcjaeger** [comment] 2017-11-22 13:48
duplicate of #675

**Closed by mcjaeger** 2017-11-22 13:48 UTC
Labels: enhancement
