### ISSUE TITLE
Licence search is case sensitive

### ISSUE THREAD

**Issue by Herschdorfer** [sw360/sw360portal#478] opened 2017-07-05 08:39 UTC
When i search for a license for adding to a component. then this search is case sensitive.

**Comment by bs-jokri** [comment] 2017-07-05 09:20
Relates to #458

**Comment by maximilianhuber** [comment] 2017-07-05 12:25
Duplicate of https://github.com/sw360/sw360portal/issues/348

**Comment by mcjaeger** [comment] 2017-07-05 12:27
But thanks for contributing an issue to us! :)

**Comment by Herschdorfer** [comment] 2017-07-05 12:52
NP :)

**Comment by Herschdorfer** [comment] 2017-07-05 13:19
made a fix #479

**Closed** 2017-07-11 14:30 UTC
Labels: duplicate
