### ISSUE TITLE
Adding release with non-existing name results in AddDocumentRequestStatus.DUPLICATE

### ISSUE THREAD

**Issue by toedter** [sw360/sw360portal#317] opened 2017-01-05 13:35 UTC
I found this bug when I wanted to add 2 releases with the names "spring-webmvc" and "spring-web".
After successfully adding "spring-webmvc", adding "spring-web" results in AddDocumentRequestStatus.DUPLICATE.

It seems that the duplicate matching is not done with the exact name, but with kind of "contains" relation, since "spring-web" is contained in "spring-webmvc"

**Comment by alex-evo** [comment] 2017-02-20 12:47
Cannot reproduce the problem.
Successfully created components with those names and releases, too.
![screenshot from 2017-02-20 13 45 03](https://cloud.githubusercontent.com/assets/16780167/23125625/0b564d9e-f773-11e6-9f1f-f199733d9c03.png)
![screenshot from 2017-02-20 13 45 33](https://cloud.githubusercontent.com/assets/16780167/23125626/0b57cef8-f773-11e6-8d73-1a2fd0454846.png)

Looking into the code confirms that components are matched by the complete name for the duplicate check and releases are matched by name *and* version.

I'm closing the issue. Please reopen if you can reproduce the problem with the current master.

**Comment by toedter** [comment] 2017-02-20 17:26
Alex, I tested against the Thrift API, not the portal UI. I will check with the latest release.

**Comment by mcjaeger** [comment] 2017-05-19 12:20
I am having this too now! in 17 cases with a larger import dataset

**Comment by toedter** [comment] 2017-05-19 12:32
Michael, then I reopen this bug.

**Comment by alex-evo** [comment] 2017-05-19 13:18
I can see now what my mistake was when I tested this. I've created a release with a different version, as seen on the screeshot. Testing with a part of an existing name and the same version reveals the error.

**Closed** 2017-05-22 15:15 UTC
Labels: bug, needs review, Size S
