### ISSUE TITLE
Editing Project or Component defaults to Summary

### ISSUE THREAD

**Issue by daral** [sw360/sw360portal#495] opened 2017-07-12 16:29 UTC
When Edit is clicked even if you are on a different tab such as Attachements, or Clearing Status the page defaults to the Summary tab. 
Is it possible to enhance this in the future to open the Edit page for the tab we are in?
Thanks

**Comment by alexbrdn** [comment] 2017-07-13 07:11
Duplicate of #104

**Closed by alexbrdn** 2017-07-13 07:11 UTC
