### ISSUE TITLE
Refresh Status with Fossology Failed

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#176] opened 2016-05-20 12:36 UTC
After having uploaded a release source file attachment to fossology, the update status failed. The message in the log is:
` 2016-05-20 12:33:26 ERROR FossologyUploader:132 - get status in fossology failed:`
(note that the reason for fossology is missing after the double colon)
The screenshot what theuser sees is attached.
Since the upload to Fossology works, the assumption is that the connection generally works.
![036 oss sw360 20160520 screenshot sent to fossology failed](https://cloud.githubusercontent.com/assets/3418977/15427866/3d5286dc-1e98-11e6-9042-89e4c641a99d.png)

**Comment by mcjaeger** [comment] 2016-06-17 11:53
group discussion: apparently it is because there is a problem with the jobs that are not kicked off from the sw360 upload.

**Comment by alex-evo** [comment] 2016-08-22 06:53
As discussed, closing this as "Can't reproduce"

**Closed by alex-evo** 2016-08-22 06:53 UTC
Labels: bug, ready
